name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  push:
    branches:
      - main  
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Update README with GitHub Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        # Note: This step is optional and only works if you have Wakatime setup
        # You can remove it if you don't use Wakatime
        continue-on-error: true
        
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Auto-update GitHub stats [skip ci]"
          git push
